### ISSUE TITLE
Created a c-sharp ML.NET project using dotnet new command in command prompt but can't open in VS2017

### ISSUE THREAD

**Issue by piyush-varma** [dotnet/machinelearning-samples#373] opened 2019-04-17 22:38 UTC
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/run
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by CESARDELATORRE** [comment] 2019-04-17 23:14
Can you provide further details on the steps you did?
We have tested that the mentioned getting started tutorial works on Windows and macOS: https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/run

It might be something related to your environment (CLI or VS)?

**Comment by prathyusha12345** [comment] 2019-04-23 17:14
@piyush-varma Are you still getting the error? I am closing the issue hoping the issue is resolved. Please reopen if you encounter any issues. Ok ?

Thanks.

**Closed by prathyusha12345** 2019-04-23 17:14 UTC
