### ISSUE TITLE
[Question] How to predict a simple sequence?

### ISSUE THREAD

**Issue by kerohero** [dotnet/machinelearning-samples#191] opened 2019-01-04 19:08 UTC
If I have a sequence like (1, 3, 5, 7, 9, 11) 
How to predict 13 using ML .NET? 

```
public class Program
    {
        public class Data
        {
            public int X, Y;
        }
        public class Res
        {
            public int Y;
        }
        static IEnumerable<Data> GetData()
        {
            var y = 1;
            for (var i = 0; i < 20; i++)
            {
                yield return new Data() { X = i, Y = y };
                y += 2;
            }
        }
        static void Main(string[] args)
        {
            var mlContext = new MLContext();

            IEnumerable<Data> data = GetData();

            var trainData = mlContext.CreateStreamingDataView(data);

            var trainingPipeline = /* NO IDEA WHAT TO DO HERE*/;  
            var model = trainingPipeline.Fit(trainData);

            var prediction = model.MakePredictionFunction<Data, Res>(mlContext).Predict(new Data() { X = 4 });
            Console.WriteLine($"Predicted is: {prediction.Y}");
        }
    }

```
It's maybe a stupid question to ask, but I find it really hard to get into Machine Learning with .NET if you have any source I can learn from, please share it...

**Comment by CESARDELATORRE** [comment] 2019-01-08 17:42
If you want to predict "a number" based on historic data (Historic numbers/labels), usually you solve that problem with a regression model.
Take a look to the 
That doesn't mean that for a very specific series of numbers, like "1, 3, 5, 7, 9, 11" you should use a regression because that is a very strict and math based oriented series and can be solved with a math rule/calculation.
Regression works good for you when, precisely, you cannot base your algorithm on any math formula but you do have a historic series of numbers and you'd like to predict the next numbers.
Examples: Forecast, Price of products, Price of houses, Price of cars, etc. You have a bunch of data (features, like in a car, car's characteristics) and related to that data you have actual prices. 
Then, you create a regression model and that model can predict a price/number based on the related provided features.

Examples for regression problems:
 
Price prediction:  https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/Regression_TaxiFarePrediction     

Sales forecast:     https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/end-to-end-apps/Regression-SalesForecast

Demand prediction:     https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/getting-started/Regression_BikeSharingDemand

Key takeaway: When you want to predict a value/number, usually that'll be a REGRESSION problem.
But if time/seasons/periods are related, then TIME SERIES based models can be a better solution.

Hope it helps. Closing the issue, ok? 👍

**Closed by CESARDELATORRE** 2019-01-08 17:42 UTC

**Comment by kerohero** [comment] 2019-01-08 18:15
It is ok to close the issue. Where can I find samples for Time series predictions?

**Comment by kerohero** [comment] 2019-01-09 16:33
@CESARDELATORRE
