### ISSUE TITLE
Error CS0411

### ISSUE THREAD

**Issue by quanghoahcm** [dotnet/machinelearning-samples#475] opened 2019-05-22 09:54 UTC
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/consume
Operating System: macos

/Users/quanghoa/MyMLApp/consumeModelApp/Program.cs(46,46): Error CS0411: The type arguments for method 'ModelOperationsCatalog.CreatePredictionEngine<TSrc, TDst>(ITransformer, bool, SchemaDefinition, SchemaDefinition)' cannot be inferred from the usage. Try specifying the type arguments explicitly. (CS0411) (consumeModelApp)

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by prathyusha12345** [comment] 2019-05-22 19:48
Can you try changing the statement to below in program.cs file of ConsumeModelApp project.

`var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
`

Meanwhile we are fixing the issue in tutorial.

**Comment by prathyusha12345** [comment] 2019-05-22 20:51
The issue is fixed now. I am closing the issue. Thanks 👍

**Closed** 2019-05-22 20:51 UTC
