### ISSUE TITLE
Relative paths to Data and MLModels folders are incorrect for most sample apps

### ISSUE THREAD

**Issue by ruslanss** [dotnet/machinelearning-samples#144] opened 2018-11-28 23:09 UTC
Not sure if it's just "my machine" or because I'm on Windows (10) but the paths to "Data" and "MLModels" appear to be going 3 level up too many.

e.g.
       ` private static string BaseModelsPath = @"../../../../MLModels";`
        s/b:
       ` private static string BaseModelsPath = @"../MLModels";`

**Comment by CESARDELATORRE** [comment] 2018-11-28 23:19
What sample app is not working for you? I'm testing all the samples in Windows 10 and it works okay.
If you are getting the error on "max characters in path", try setting the base path to a shorter folder path?

In my case I have the following "base path" (which is not short) for all the samples (GitHub repo), and it works properly:
C:\GitRepos\machinelearning-samples-CESAR-master\

**Comment by ruslanss** [comment] 2018-11-28 23:43
hey, i haven't changed any settings or properties. just cloned the repo and opened the v0.7-All-Samples.sln

so, with TaxiFarePredictionConsoleApp example, i can see that the Output path is set to: `bin\Debug\netcoreapp2.0\` and yet it still fails with the following error:

`DirectoryNotFoundException: Could not find a part of the path 'C:\git\machinelearning-samples\samples\csharp\Data\taxi-fare-train.csv'.`

on line 167: ` var transformer = pipeline.Fit(dataView);`

**Comment by ruslanss** [comment] 2018-11-28 23:45
...does seem strange that the executing directory for me appears to be the folder where `Program.cs` file is, what gives?

**Comment by ruslanss** [comment] 2018-11-28 23:50
just checked in `Regression_TaxiFarePrediction.Program`, while executing in Debug mode with F5 from Visual Studio 2017, `Directory.GetCurrentDirectory();` returns: `C:\git\machinelearning-samples\samples\csharp\getting-started\Regression_TaxiFarePrediction\TaxiFarePrediction\TaxiFarePredictionConsoleApp` for me.

**Comment by ruslanss** [comment] 2018-11-28 23:53
are you running from VS also?

**Comment by CESARDELATORRE** [comment] 2018-11-28 23:55
Yes, we're usually using VS. I'm precisely testing/modifying the `Regression_TaxiFarePrediction.Program` today with no issues when using that path..

Mmmm, when possible, can you try in a different machine with the by-default VS installation? - These samples are tested almost daily by multiple people and this is the first notice about that behavior you mention.

**Comment by CESARDELATORRE** [comment] 2018-11-28 23:59
I just tested the latest version of `TaxiFarePrediction`:

![image](https://user-images.githubusercontent.com/1712635/49190285-84602380-f326-11e8-8996-ae58da8877f4.png)

I wonder why that difference in your environment..

**Comment by ruslanss** [comment] 2018-11-29 00:14
just pulled v0.8 and still having the same problem. i'm sure it must be specific to my machine. i use VS 2017 Community with Resharper 2018.2

![clipboard01](https://user-images.githubusercontent.com/1591905/49190763-96b08080-f36b-11e8-8bbf-f6402ec2961e.jpg)

i shall give it a go on another machine tomorrow. it's getting late here in UK :)

**Comment by CESARDELATORRE** [comment] 2018-11-30 19:00
I think this is a local environment issue since I cannot reproduce it. I'm closing this issue but feel free to re-open if you reproduce it in another machine. If so, please tell us what do you think it is causing the differences in behavior. Thanks for your feedback. 👍

**Closed by CESARDELATORRE** 2018-11-30 19:00 UTC
Labels: bug
