### ISSUE TITLE
MNIST testing (With Image files)

### ISSUE THREAD

**Issue by developervariety** [dotnet/machinelearning-samples#461] opened 2019-05-16 15:30 UTC
How would you go about loading an image and detecting the numbers on an image?

Is it possible to detect more than one digit at a time?

**Comment by CESARDELATORRE** [comment] 2019-05-16 16:19
The native ML.NET algorithms/trainers currently focus on traditional machine learning working with data (text, numbers, values, etc.) for ML tasks such as classification, regression, recommendations, anomaly-detection, etc.

However, loading/processing images requires a model created with a Deep Learning framework such as TensorFlow or any other deep learning framework. Then, with ML.NET you can run/use/score that model with ML.NET API from C#.

Bottomline, what you want to do is very similar to the image classification sample we have using a TensorFlow model here: 

https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/getting-started/DeepLearning_ImageClassification_TensorFlow

However, in that sample we're using a pretrained TensofFlow model named 'Inception v3' which is great for many objects/pictures such as people, animals, plants, cars, etc. but not good for MNIST.

For doing the same with MNIST images you need to find a pre-trained TensorFlow model that was trained for MNIST (white background with a written number on each image), then you can run it with ML.NET API by loading the TensorFlow model (.pb file).

**Comment by CESARDELATORRE** [comment] 2019-05-16 16:48
Closing the issue for now since it is not a particular issue related to any sample in the repo.
Re-open if needed. Thanks for your interest in ML.NET! 👍

**Closed by CESARDELATORRE** 2019-05-16 16:48 UTC
