### ISSUE TITLE
Download link is not working

### ISSUE THREAD

**Issue by karthikperneti** [dotnet/machinelearning-samples#414] opened 2019-05-06 18:31 UTC
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by prathyusha12345** [comment] 2019-05-06 18:52
link is fixed now. Could you please check.

**Comment by ElGranLuisR** [comment] 2019-05-06 20:00
Still not working.

**Comment by prathyusha12345** [comment] 2019-05-06 20:35
Can you try accessing the link https://marketplace.visualstudio.com/items?itemName=MLNET.07.

**Comment by SuperDaveOsbourne** [comment] 2019-05-06 20:43
We're sorry, the page you requested cannot be found!

**Comment by rajach** [comment] 2019-05-06 20:49
I still see the same issue

**Comment by prathyusha12345** [comment] 2019-05-06 23:35
The issue is fixed now. Can you try accessing the link now .

**Comment by rustd** [comment] 2019-05-13 17:54
Please re-open this if the issue still happens.

**Closed by rustd** 2019-05-13 17:54 UTC
Labels: ModelBuilder
