### ISSUE TITLE
Problem with the Hello world sample

### ISSUE THREAD

**Issue by CyberFranck** [dotnet/machinelearning-samples#516] opened 2019-06-11 19:41 UTC
the Hello World sample here :
https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work

Third line of code does not work and i am talking of the first actual using that is not default of .net
using Microsoft.Data.DataView;

Doesn't work, doesn't see it. Nuget is latest version, tried to upgrade up to .net 4.8. Added Nuget package Microsoft.ML. Compiled the project with nothing and it run fine.

Actual reference in the project show the following (on an empty console application)
![image](https://user-images.githubusercontent.com/50143000/59301335-5e192a00-8c5f-11e9-8a67-cc43a10831e0.png)

**Comment by CESARDELATORRE** [comment] 2019-06-11 20:23
It should be just this:

`using Microsoft.ML.Data;`

`Microsoft.Data.DataView` is a deprecated namespace from beta/preview versions.

That code snippet needs to be updated.

**Comment by CESARDELATORRE** [comment] 2019-06-11 20:28
Making that change I provided above, the code works, see here:

![image](https://user-images.githubusercontent.com/1712635/59304286-c7dc0880-8c4c-11e9-93f8-6785aaf23acb.png)

**Comment by CESARDELATORRE** [comment] 2019-06-11 20:30
Closing this issue since I opened in the docs.microsoft.com repo/site here (Feedback/issues at the end of the page):

https://docs.microsoft.com/en-us/dotnet/machine-learning/how-does-mldotnet-work

**Closed by CESARDELATORRE** 2019-06-11 20:30 UTC

**Comment by CyberFranck** [comment] 2019-06-12 13:39
Nope it didn't fix it. We played around and someone tried to add .NetCore to the project and suddenly it worked. No mention to .netcore requirement anywhere easy to find.

**Comment by natke** [comment] 2019-06-12 20:39
Hi @CyberFranck, we could not reproduce this error. The sample runs using .NET Framework
