### ISSUE TITLE
Question : who can i generate the model using 64 bit application and predict the result from 32 bit 

### ISSUE THREAD

**Issue by DevLob-zz** [dotnet/machinelearning-samples#216] opened 2019-01-28 11:11 UTC
Question : who can i generate the model using 64 bit application and predict the result from 32 bit ?

i forced to use 32 bit application and i think about work around 

to separate the generate model file using 64 bit to overcome out of memory due to 32 bit in case large data 

and make a predictor using 32 bit which i can not able to make it 64 bit but while load the already generated model it throw an exception 

"'Could not load type 'Microsoft.ML.Transforms.Categorical.CategoricalTransform' from assembly 'Microsoft.ML.Transforms, Version=1.0.0.0, Culture=neutral"

is this approach is wrong  ? and is there is another solution for that 

please advice best regards

**Comment by CESARDELATORRE** [comment] 2019-01-28 17:15
I initially think that training the model in a x64 app and scoring in a different x86 app should be possible. That is what you mean, right?
Adding @glebuk and @eerhardt to confirm.

**Comment by DevLob-zz** [comment] 2019-01-28 18:32
Yes Exactly

**Comment by CESARDELATORRE** [comment] 2019-01-28 20:04
What you are trying to do should be possible as one of the scenarios for ML.NET. 
You might have found a bug in ML.NET. Please, if confirmed the same errors in different environments, open an ISSUE/BUG in the ML.NET repo, here:
https://github.com/dotnet/machinelearning/issues

**Comment by CESARDELATORRE** [comment] 2019-01-29 00:12
Closing this issue since this is an issue related to ML.NET itself, not about the Samples.
Thanks for catching this up, anyways! 👍

**Closed by CESARDELATORRE** 2019-01-29 00:12 UTC
