### ISSUE TITLE
Exception in PredictionEngineBase when using Time Series model with PredictionEnginePool

### ISSUE THREAD

**Issue by NeoXtreem** [dotnet/machinelearning-samples#739] opened 2019-11-06 23:28 UTC
I've created a Time Series model using the method described [here](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/Forecasting-Sales) resulting in this code:
```cs
var data = items.ToArray();
var trainData = mlContext.Data.LoadFromEnumerable(data);

var estimator = mlContext.Forecasting.ForecastBySsa(
    nameof(FooPrediction.BarPrediction),
    nameof(FooInput.Bar),
    12,
    data.Length,
    data.Length,
    2,
    confidenceLowerBoundColumn: nameof(FooPrediction.ConfidenceLowerBound),
    confidenceUpperBoundColumn: nameof(FooPrediction.ConfidenceUpperBound));

var transformer = estimator.Fit(trainData);
using var engine = transformer.CreateTimeSeriesEngine<FooInput, FooPrediction>(mlContext);
engine.CheckPoint(mlContext, "model.zip");
```

...where `items` is `IEnumerable<FooInput>`.

These are my model classes:
```cs
public class FooPrediction
{
    public float[] BarPrediction { get; set; }

    public float[] ConfidenceLowerBound { get; set; }

    public float[] ConfidenceUpperBound { get; set; }
}

public class FooInput
{
    public float Bar { get; set; }

    public float Baz { get; set; }
}
```

In my `Startup`, I add a `PredictionEnginePool` thus:
```cs
services.AddPredictionEnginePool<FooInput, FooPrediction>().FromFile(String.Empty, "model.zip", true);
```

In my middleware service, I inject the `PredictionEnginePool` and then call:
```cs
var prediction = items.Select(i => predictionEnginePool.Predict(i));
```

...where `items` is `IEnumerable<FooInput>`.

This results in an `ArgumentOutOfRangeException` being thrown in `PredictionEngineBase.TransformerChecker`:

> Must be a row to row mapper (Parameter 'transformer')

Debugging into the code, I can see there is a check for `IsRowToRowMapper` on the `ITransformer` object being true. However, when the model is created, an `SsaForecastingTransformer` is created which has this property set to false.

Am I doing something wrong, or does `PredictionEnginePool` not support Time Series models?

I've also tried this with `AddPredictionEnginePool<IEnumerable<FooInput>, FooPrediction>` and then calling `predictionEnginePool.Predict(items)`, but this also results in the same exception.

**Comment by CESARDELATORRE** [comment] 2019-11-08 21:56
Adding @eerhardt in case he want to add something else.

As you can see in the sample you pointed out, we use the PredictionEnginePool only for the Regression model, not for the TimeSeries-Forecast model.

TimeSeries-Forecast is a very different approach/implementation compared to most of the algorithms in ML.NET due to its nature (Time Series). In fact, it has a specially-made Prediction Engine which is called `TimeSeriesPredictionEngine`. It does not use the regular `PredictionEngine`, as you can see in this controller using the `TimeSeriesPredictionEngine`:

https://github.com/dotnet/machinelearning-samples/blob/master/samples/csharp/end-to-end-apps/Forecasting-Sales/src/eShopDashboard/Controllers/ProductTimeSeriesForecastController.cs#L58

Therefore, right, the `PredictionEnginePool `does not support Time Series based models.
In this case, please, use it as shown in the code above.

I'm closing the issue for now, but feel free to re-open if needed, ok?
Thanks! 👍

**Closed by CESARDELATORRE** 2019-11-08 21:56 UTC

**Comment by NeoXtreem** [comment] 2019-11-11 09:12
@CESARDELATORRE Thanks for the reply and clarification. A [similar answer](https://stackoverflow.com/a/58795494/197591) was given on the SO question I raised for this, referring to the statefulness of Time Series. I'll refactor my code to use `TimeSeriesPredictionEngine` in the case of Time Series models then. Thanks!
