### ISSUE TITLE
Publish Object Detection End-to-End APP to web app failed

### ISSUE THREAD

**Issue by jeremywangyuan** [dotnet/machinelearning-samples#448] opened 2019-05-13 09:10 UTC
Hi, I am trying the sample https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/DeepLearning_ObjectDetection_Onnx .
I can successfully build and test on localhost. 
And I follow the step https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-dotnet#launch-the-publish-wizard to publish. 
But I didnt get any result after I click Upload File. 
Any suggestions or tips ? Thanks.

**Comment by prathyusha12345** [comment] 2019-05-14 17:28
Are there any logs available to check the issue?

**Comment by prathyusha12345** [comment] 2019-05-21 21:24
There is an issue in loading native dlls in Azure app Service. I am assigning the issue to ONNX model team.

@jignparm ,@clauren42 I am assigning the issue. or Do I need to create an issue in other repo?

**Comment by CESARDELATORRE** [comment] 2019-05-21 21:27
Please, open the issue at the ML.NET repo since this might be a platform issue not really related to samples.

**Comment by jignparm** [comment] 2019-05-29 22:28
@prathyusha12345, @jeremywangyuan - it seems like this is an issue when deploying into Azure App service, and cannot be reproduced locally. May require following up with Azure web app folks instead. Please link this issue with an appropriate issue for web services.

**Comment by prathyusha12345** [comment] 2019-05-29 23:14
Closing this issue as its not related samples. As mentioned above please open this issue at ML.Net repo.

**Closed by prathyusha12345** 2019-05-29 23:14 UTC
