### ISSUE TITLE
Basic references are missing like System.Console, System.String

### ISSUE THREAD

**Issue by ivikashjha** [dotnet/machinelearning-samples#452] opened 2019-05-14 11:45 UTC
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/consume
Operating System: windows

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

**Comment by rustd** [comment] 2019-05-14 19:34
Can you please add more info on where are these references missing?

**Comment by ivikashjha** [comment] 2019-05-22 07:53
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0266	Cannot implicitly convert type 'Microsoft.ML.IDataView' to 'System.Data.DataView'. An explicit conversion exists (are you missing a cast?)	myMLAppML.ConsoleApp	C:\Users\vikash.ranjan.jha\source\repos\myMLApp\myMLAppML.ConsoleApp\Program.cs	52	Active

**Comment by ivikashjha** [comment] 2019-05-22 07:56
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'System.Data.DataView' to 'Microsoft.ML.IDataView'	myMLAppML.ConsoleApp	C:\Users\vikash.ranjan.jha\source\repos\myMLApp\myMLAppML.ConsoleApp\Program.cs	60	Active
Error	CS0266	Cannot implicitly convert type 'Microsoft.ML.IDataView' to 'System.Data.DataView'. An explicit conversion exists (are you missing a cast?)	myMLAppML.ConsoleApp	C:\Users\vikash.ranjan.jha\source\repos\myMLApp\myMLAppML.ConsoleApp\Program.cs	52	Active

**Comment by rustd** [comment] 2019-06-03 21:10
@ivikashjha can you please add more details here? https://github.com/dotnet/machinelearning-modelbuilder/issues/91

**Comment by rustd** [comment] 2019-06-27 20:45
Duplicate of https://github.com/dotnet/machinelearning-modelbuilder/issues/65 so closing this issue.

**Closed by rustd** 2019-06-27 20:45 UTC
Labels: ModelBuilder
