### ISSUE TITLE
unable to install Microsoft.ML package

### ISSUE THREAD

**Issue by dotnotguy** [dotnet/machinelearning-samples#294] opened 2019-03-04 14:39 UTC
Problem encountered on https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/install-package
Operating System: windows 10

Provide details about the problem you are experiencing. Include your operating system version, exact error message, code sample, and anything else that is relevant.

I'm running Windows 10 with VS 17 Enterprise and when I try to add the package package Microsoft.ML --version 0.10.0, I get an error message:
I have set the project to several version of the .NET framework and still get the message below
Severity	Code	Description	Project	File	Line	Suppression State
Error	Could not install package 'Microsoft.ML 0.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	0

**Comment by dotnotguy** [comment] 2019-03-04 14:40
I'm running Windows 10 with VS 17 Enterprise and when I try to add the package package Microsoft.ML --version 0.10.0, I get an error message: 
I have set the project to several version of the .NET framework and still get the message below
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.ML 0.10.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by CESARDELATORRE** [comment] 2019-03-04 17:15
What version of .NET Framework are you using when getting that issue?
- .NET Framework x64 ?
- .NET Framework x86 ?

**Comment by dotnotguy** [comment] 2019-03-04 17:25
x64

**Comment by CESARDELATORRE** [comment] 2019-03-05 18:43
I think the issue is that you're using .NET Framework 4.6.
As stated in the ML.NET repo, the supported versions are:

> ML.NET runs on Windows, Linux, and macOS using .NET Core, or **Windows using .NET Framework. 64 bit is supported on all platforms. 32 bit is supported on Windows, except for TensorFlow, LightGBM, and ONNX related functionality.**
> 
> The current release is 0.10. Check out the release notes to see what's new.
> 
> First, ensure you have installed .NET Core 2.1 or later. **ML.NET also works on the .NET Framework 4.6.1 or later, but 4.7.2 or later is recommended**.

I just tested the getting started sample on VS and .NET framework 4.6.1, and it works as expected:
https://dotnet.microsoft.com/learn/machinelearning-ai/ml-dotnet-get-started-tutorial/

Here's the project config in Visual Studio for x64:

![image](https://user-images.githubusercontent.com/1712635/53828517-c35bd180-3f32-11e9-8d7b-f3170f9f32d1.png)


Here's the Iris classification sample app working on .NET Framework 4.6.1 console app:
![image](https://user-images.githubusercontent.com/1712635/53828487-a921f380-3f32-11e9-8a31-3c342a31f500.png)

As mentioned, make sure you are using:
-  .NET Framework 4.6.1 or later.
- .NET Core 2.1 or later

Hope that helps,

(Closing the issue, unless needed again)

**Closed by CESARDELATORRE** 2019-03-05 18:43 UTC
