### ISSUE TITLE
Expected Vector<R4> got Vector<Text>

### ISSUE THREAD

**Issue by chefbennyj1** [dotnet/machinelearning-samples#339] opened 2019-03-30 16:26 UTC
Good day,

I attempting a project which utilizes ML.Net to (maybe) learn my families routines with regards to my Home Automation.

Currently, I have been creating a Dataset in CSV format. It looks like this:

`Day,TimeOfDay,Device,State
6,0827,999,1
6,0827,117,1
6,0827,117,0
6,0838,18,1
6,0838,79,1
6,0838,6,1
6,0901,117,1
6,0908,999,0
6,0910,73,0
6,0913,72,1
6,0914,72,0
6,0915,79,0
6,0915,6,0
6,0915,5,0
6,0915,4,0
6,0915,18,0
6,1015,18,1
6,1015,79,1
6,1015,6,1
6,1015,5,1
6,1015,4,1`

I was hoping to follow some kind of prediction model which would eventually predict our routines.

I'm finding this a little complicated.

When trying to load a DataView, I receive an error:

"expecting Vector R4 but got Vector Text".

I've been attempting to follow the github repos to try and figure out exactly what this means. I'm pretty sure that Vector R4  is an integer... float? ... and I am trying to feed it strings (even though they're ints).

I would love some guidance. I am trying to follow the iris classification project.

Thank you.

**Comment by prathyusha12345** [comment] 2019-04-02 18:27
chefbennyj1 Could you let me know how you are loading the data and what kind of transformations you are doing?

The error "expecting Vector R4 but got Vector Text" means the trainer expects **float** but you are providing **text**. Please transform the text into  numeric value. 

The names **I4** and **Vector R4** means int and float for the purposes of our data view type system.
Please see the [extensive type system doc](https://github.com/dotnet/machinelearning/blob/master/docs/code/IDataViewTypeSystem.md) for full insight into the type system.

Please let me know if you still face any issue or need any help, ok?

Thanks

**Comment by prathyusha12345** [comment] 2019-04-04 16:31
@chefbennyj1 Is your issue resolved? 

I am closing issue hoping the issue is resolved. Please reopen if you encounter issue again. Thanks

**Closed by prathyusha12345** 2019-04-04 16:31 UTC
