### ISSUE TITLE
what is the difference between RandomizedPca and DetectIidSpike?

### ISSUE THREAD

**Issue by jigarhshah17** [dotnet/machinelearning-samples#673] opened 2019-10-01 08:52 UTC
hi i have temperature data with column name (temperature,month,day,hour,minute,second)
i want to know abnormal data so which one i have to used ?

**Comment by CESARDELATORRE** [comment] 2019-10-01 17:14
RandomizedPCA is more for cases where you have labeled data and want to classify, for instance, Fraud Detection. The problem is very similar to a Binary classification but this scenario usually targets imbalance datasets where one of the cases (like IsFraud) has most of them false (i.e. 99% ara false) and just 1% is true, because imbalanced datasets might not work well with Binary Classification algorithms.

Then, DetectIidSpike is for detecting spikes in data related to time series data, like detecting spikes in power consumption or sales, etc.

If this info helps you, feel free to close the issue, ok?

**Comment by CESARDELATORRE** [comment] 2019-10-11 17:06
Closing this issue as it was responded days ago.

**Closed by CESARDELATORRE** 2019-10-11 17:06 UTC

**Comment by jigarhshah17** [comment] 2019-12-18 13:46
@CESARDELATORRE  https://github.com/dotnet/machinelearning/issues/4575#issuecomment-567031177
Please help me

**Comment by IveJ** [comment] 2019-12-18 15:52
Hi Friend,

@ DetectIdSpike create IidSpikeEstimator, for predict spikes in i.i.d time
series base on adaptive kenel density estimations and martingale score.

@ RandomizedPca create RandomizedPcaTrainer with advanced options, which
trains an approximate principal component analysis (PCA) model using
randomized singular value decomposition (SVD) algorithm.
